### ISSUE TITLE
ConvBert模型与原版的误差

### ISSUE THREAD

**Issue by JunnYu** [RookieZB/bert_implementation_by_tf2#1]
首先感谢你用tf2.x实现了ConvBert代码，我之前也简单的学习过tf2.x的代码，其次我想问一下，为啥我感觉误差有点大。
small模型输出的最大误差 1.169890e-04
base模型输出的最大误差  2.193451e-04
我感觉同种框架下的误差应该不是-4次方级别的，可能实现的时候与原版有点差异。

**Comment by RookieZB** [comment]
你好，我用哈工大中文ELECTRA（small）对文本“我爱学习。”做了编码，结果如下，
HuggingFace结果与原版误差平均2.10587e-09（最大2.026558e-06）；
我这边结果与原版误差平均2.6894279e-08（最大3.695488e-05）。
所以，我认为此类误差尚属可接受正常范围，毕竟代码中函数、常数的选用多少会与原版TF1存在差异，甚至同一代码对padding与否的文本编码也会产生差异。使用原模型做MLM预测或者对模型finetune时，这样的误差也不会产生影响。我的复现主要是参考TF2官方的Transformer代码修改的，当然也不排除我在一些细节处理中的疏忽。
此外，我看到你好像实现了PyTorch版本，想确认下ConvBERT相比ELECTRA在推理速度上能够提升多少？谢谢。

**Comment by JunnYu** [comment]
@RookieZB 
```python
(hg_out-tf_out).abs().max() # 最大误差 3.7909e-05
(hg_out-tf_out).abs().mean() # 平均误差5.2314e-06
```
# huggingface与你的代码比较
https://colab.research.google.com/drive/1VI8ZKMlfuRsUeCNJ5KLJrF0pp_mwSkTc?usp=sharing

# 谷歌原版与huggingface比较
https://colab.research.google.com/drive/1tRTOR4tu779typ9a1u6TsneLjp5IN6tU?usp=sharing
我这测试的SST2，用了fastai跑了下，感觉convbert总体时间比electra花费的要长。
![1605877886(1)](https://user-images.githubusercontent.com/50394665/99803831-07fb2680-2b75-11eb-84f9-127baefa2e19.jpg)

**Comment by RookieZB** [comment]
@JunnYu 谢谢，所以我认为这样数量级的误差应该可以接受？当然我的复现肯定不及HuggingFace的TF2代码细致，毕竟主要目的是帮助自己学习，见谅。
我这边测试也是慢于同规格ELECTRA，和论文中“速度快”的优点相悖，比较疑惑。只能看看以后别人如何复现出这一效果。

**Comment by JunnYu** [comment]
@RookieZB 我很喜欢你写的代码，我也从你的tf2.x的代码中学到了很多。我有个问题，你能帮我看下我上面的【谷歌原版与huggingface比较的代码】https://colab.research.google.com/drive/1tRTOR4tu779typ9a1u6TsneLjp5IN6tU?usp=sharing 吗？为啥我感觉最大误差差距有那么大？是我比较的代码写错了吗？
如果可以的话，我想看看你比较的代码，谢谢！

**Comment by RookieZB** [comment]
@JunnYu 我这边结果确实和你不同，用的是哈工大那份代码，不确定是否是这个原因。我稍后把测试代码发你邮箱吧。
